/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import type { FriendRequestStatus } from "@ab/shared/friends"
import type { Category as ResourceCategory } from "@ab/shared/categories"

/**
 * Lean version of AccountabilityPartnershipDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AccountabilityPartnershipDocument.toObject()`. To avoid conflicts with model names, use the type alias `AccountabilityPartnershipObject`.
 * ```
 * const accountabilitypartnershipObject = accountabilitypartnership.toObject();
 * ```
 */
export type AccountabilityPartnership = {
  user1: User["_id"] | User
  user2: User["_id"] | User
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of ActivityDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ActivityDocument.toObject()`. To avoid conflicts with model names, use the type alias `ActivityObject`.
 * ```
 * const activityObject = activity.toObject();
 * ```
 */
export type Activity = {
  user: User["_id"] | User
  type:
    | "goal"
    | "reminder"
    | "post"
    | "message"
    | "login"
    | "logout"
    | "signup"
    | "friend_request"
    | "friend_accept"
    | "comment"
    | "reaction"
    | "achievement"
  description: string
  metadata?: any
  participants: (User["_id"] | User)[]
  isDeleted?: boolean
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of AnonymousMilitaryMessageDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AnonymousMilitaryMessageDocument.toObject()`. To avoid conflicts with model names, use the type alias `AnonymousMilitaryMessageObject`.
 * ```
 * const anonymousmilitarymessageObject = anonymousmilitarymessage.toObject();
 * ```
 */
export type AnonymousMilitaryMessage = {
  room: "veterans-support" | "active-duty" | "family-members"
  anonymousSessionId: string
  displayName: string
  message: string
  isFlagged?: boolean
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of AnonymousSessionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AnonymousSessionDocument.toObject()`. To avoid conflicts with model names, use the type alias `AnonymousSessionObject`.
 * ```
 * const anonymoussessionObject = anonymoussession.toObject();
 * ```
 */
export type AnonymousSession = {
  sessionId: string
  displayName: string
  room: "veterans-support" | "active-duty" | "family-members"
  lastActive?: string
  joinedAt?: string
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of AnonymousMoodCheckInDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `AnonymousMoodCheckInDocument.toObject()`. To avoid conflicts with model names, use the type alias `AnonymousMoodCheckInObject`.
 * ```
 * const anonymousmoodcheckinObject = anonymousmoodcheckin.toObject();
 * ```
 */
export type AnonymousMoodCheckIn = {
  sessionId: string
  mood: number
  note?: string | null
  ipAddress?: string | null
  userAgent?: string | null
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of BadgeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BadgeDocument.toObject()`. To avoid conflicts with model names, use the type alias `BadgeObject`.
 * ```
 * const badgeObject = badge.toObject();
 * ```
 */
export type Badge = {
  user: User["_id"] | User
  badgeType: BadgeType["_id"] | BadgeType
  level?: "Bronze" | "Silver" | "Gold"
  progress?: number
  dateAwarded?: string
  isShowcased?: boolean
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of BadgeTypeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BadgeTypeDocument.toObject()`. To avoid conflicts with model names, use the type alias `BadgeTypeObject`.
 * ```
 * const badgetypeObject = badgetype.toObject();
 * ```
 */
export type BadgeType = {
  name: string
  description?: string
  bronzePointsToAward?: number
  silverPointsToAward?: number
  goldPointsToAward?: number
  iconKey?: string
  conditionToMeet: "goal_completed" | "consistency_master" | "point_earner"
  bronzeAmountRequired?: number
  silverAmountRequired?: number
  goldAmountRequired?: number
  expiresAt?: string
  _id: string
  createdAt?: string
  updatedAt?: string
  isExpired: boolean
}

/**
 * Lean version of BookCommentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BookDocument.toObject()`.
 * ```
 * const bookObject = book.toObject();
 * ```
 */
export type BookComment = {
  user: User["_id"] | User
  text: string
  createdAt?: string
  _id: string
}

/**
 * Lean version of BookDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `BookDocument.toObject()`. To avoid conflicts with model names, use the type alias `BookObject`.
 * ```
 * const bookObject = book.toObject();
 * ```
 */
export type Book = {
  title: string
  author: string
  category: string
  description: string
  coverImage?: string
  addedBy: User["_id"] | User
  likes: (User["_id"] | User)[]
  comments: BookComment[]
  _id: string
  createdAt?: string
  updatedAt?: string
  likeCount: number
  commentCount: number
}

/**
 * Lean version of ChatUnreadMessageDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ChatDocument.toObject()`.
 * ```
 * const chatObject = chat.toObject();
 * ```
 */
export type ChatUnreadMessage = {
  userId: User["_id"] | User
  count?: number
  _id: string
}

/**
 * Lean version of ChatDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ChatDocument.toObject()`. To avoid conflicts with model names, use the type alias `ChatObject`.
 * ```
 * const chatObject = chat.toObject();
 * ```
 */
export type Chat = {
  participants: (User["_id"] | User)[]
  messages: (Message["_id"] | Message)[]
  lastMessage?: Message["_id"] | Message
  chatType: "private" | "group"
  groupId?: Group["_id"] | Group
  unreadMessages: ChatUnreadMessage[]
  typingUsers: (User["_id"] | User)[]
  _id: string
  createdAt?: string
  updatedAt?: string
  participantCount: number
}

/**
 * Lean version of CheckInDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CheckInDocument.toObject()`. To avoid conflicts with model names, use the type alias `CheckInObject`.
 * ```
 * const checkinObject = checkin.toObject();
 * ```
 */
export type CheckIn = {
  user: User["_id"] | User
  createdAt?: string
  _id: string
}

/**
 * Lean version of CollaborationGoalDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CollaborationGoalDocument.toObject()`. To avoid conflicts with model names, use the type alias `CollaborationGoalObject`.
 * ```
 * const collaborationgoalObject = collaborationgoal.toObject();
 * ```
 */
export type CollaborationGoal = {
  title: string
  description?: string
  status?: "not-started" | "in-progress" | "completed" | "archived"
  progress?: number
  completedAt?: string
  milestones: (Milestone["_id"] | Milestone)[]
  visibility?: "public" | "private"
  createdBy: User["_id"] | User
  participants: (User["_id"] | User)[]
  target: number
  _id: string
  createdAt?: string
  updatedAt?: string
  participantCount: number
  milestoneCount: number
}

/**
 * Lean version of FaqDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `FaqDocument.toObject()`. To avoid conflicts with model names, use the type alias `FaqObject`.
 * ```
 * const faqObject = faq.toObject();
 * ```
 */
export type Faq = {
  question: string
  answer: string
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of FeedbackDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `FeedbackDocument.toObject()`. To avoid conflicts with model names, use the type alias `FeedbackObject`.
 * ```
 * const feedbackObject = feedback.toObject();
 * ```
 */
export type Feedback = {
  userId: User["_id"] | User
  message: string
  type?: "bug" | "feature-request" | "other"
  status?: "pending" | "reviewed" | "resolved"
  priority?: "low" | "medium" | "high"
  isAnonymous?: boolean
  relatedFeature?: string
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of FriendRequestDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `FriendRequestDocument.toObject()`. To avoid conflicts with model names, use the type alias `FriendRequestObject`.
 * ```
 * const friendrequestObject = friendrequest.toObject();
 * ```
 */
export type FriendRequest = {
  sender: User["_id"] | User
  recipient: User["_id"] | User
  status?: "pending" | "accepted" | "declined"
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of GoalDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `GoalDocument.toObject()`. To avoid conflicts with model names, use the type alias `GoalObject`.
 * ```
 * const goalObject = goal.toObject();
 * ```
 */
export type Goal = {
  title: string
  description?: string
  status?: "not-started" | "in-progress" | "completed" | "archived"
  progress?: number
  completedAt?: string
  milestones: (Milestone["_id"] | Milestone)[]
  visibility?: "public" | "private"
  user: User["_id"] | User
  category: string
  dueDate: string
  tags: string[]
  priority?: "high" | "medium" | "low"
  reminders: (Reminder["_id"] | Reminder)[]
  isPinned?: boolean
  points?: number
  _id: string
  createdAt?: string
  updatedAt?: string
  isActive: boolean
}

/**
 * Lean version of GroupDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `GroupDocument.toObject()`. To avoid conflicts with model names, use the type alias `GroupObject`.
 * ```
 * const groupObject = group.toObject();
 * ```
 */
export type Group = {
  name: string
  description?: string
  category: "fitness" | "study" | "career" | "lifestyle" | "creative" | "tech"
  members: (User["_id"] | User)[]
  createdBy: User["_id"] | User
  visibility?: "public" | "private"
  isActive?: boolean
  lastActivity?: string
  avatar?: string | null
  tags: string[]
  isPinned?: boolean
  _id: string
  createdAt?: string
  updatedAt?: string
  memberCount: number
  isPublic: boolean
}

/**
 * Lean version of GroupInvitationDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `GroupInvitationDocument.toObject()`. To avoid conflicts with model names, use the type alias `GroupInvitationObject`.
 * ```
 * const groupinvitationObject = groupinvitation.toObject();
 * ```
 */
export type GroupInvitation = {
  groupId: Group["_id"] | Group
  sender: User["_id"] | User
  recipient: User["_id"] | User
  status: "pending" | "accepted" | "rejected"
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of LevelDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `LevelDocument.toObject()`. To avoid conflicts with model names, use the type alias `LevelObject`.
 * ```
 * const levelObject = level.toObject();
 * ```
 */
export type Level = {
  user: User["_id"] | User
  points?: number
  level?: number
  nextLevelAt?: number
  rewards: (Reward["_id"] | Reward)[]
  lastActivity?: string
  _id: string
  createdAt?: string
  updatedAt?: string
  totalRewards: number
}

/**
 * Lean version of MessageReactionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `MessageDocument.toObject()`.
 * ```
 * const messageObject = message.toObject();
 * ```
 */
export type MessageReaction = {
  userId: User["_id"] | User
  emoji: string
  reactedAt?: string
}

/**
 * Lean version of MessageAttachmentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `MessageDocument.toObject()`.
 * ```
 * const messageObject = message.toObject();
 * ```
 */
export type MessageAttachment = {
  url: string
  type: "image" | "video" | "file"
}

/**
 * Lean version of MessageDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `MessageDocument.toObject()`. To avoid conflicts with model names, use the type alias `MessageObject`.
 * ```
 * const messageObject = message.toObject();
 * ```
 */
export type Message = {
  chatId: Chat["_id"] | Chat
  senderId: User["_id"] | User
  receiverId?: User["_id"] | User
  text?: string
  messageType: "private" | "group"
  status?: "sent" | "delivered" | "seen" | "deleted" | "edited"
  reactions: MessageReaction[]
  attachments: MessageAttachment[]
  replyTo?: Message["_id"] | Message
  _id: string
  createdAt?: string
  updatedAt?: string
  reactionCount: number
  attachmentCount: number
}

/**
 * Lean version of MilestoneDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `MilestoneDocument.toObject()`. To avoid conflicts with model names, use the type alias `MilestoneObject`.
 * ```
 * const milestoneObject = milestone.toObject();
 * ```
 */
export type Milestone = {
  title: string
  description: string
  dueDate: string
  completed?: boolean
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of ExternalSupportResourceDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ExternalSupportResourceDocument.toObject()`. To avoid conflicts with model names, use the type alias `ExternalSupportResourceObject`.
 * ```
 * const externalsupportresourceObject = externalsupportresource.toObject();
 * ```
 */
export type ExternalSupportResource = {
  title: string
  url: string
  description?: string
  category?: "hotline" | "website" | "forum" | "organization" | "other"
  isActive?: boolean
  _id: string
  createdAt?: string
  updatedAt?: string
  domain: string
}

/**
 * Lean version of NotificationDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `NotificationDocument.toObject()`. To avoid conflicts with model names, use the type alias `NotificationObject`.
 * ```
 * const notificationObject = notification.toObject();
 * ```
 */
export type Notification = {
  user: User["_id"] | User
  sender?: User["_id"] | User | null
  message: string
  type:
    | "friend_request"
    | "message"
    | "group_invite"
    | "blog_activity"
    | "goal_milestone"
    | "group_request_rejected"
    | "group_request_accepted"
    | "group_invite_accepted"
    | "group_invite_rejected"
  read?: boolean
  link?: string
  expiresAt?: string
  _id: string
  createdAt?: string
  updatedAt?: string
  isExpired: boolean
}

/**
 * Lean version of ReminderDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `ReminderDocument.toObject()`. To avoid conflicts with model names, use the type alias `ReminderObject`.
 * ```
 * const reminderObject = reminder.toObject();
 * ```
 */
export type Reminder = {
  user: User["_id"] | User
  message: string
  goal?: Goal["_id"] | Goal
  remindAt: string
  recurrence?: "none" | "daily" | "weekly" | "monthly"
  isActive?: boolean
  isSent?: boolean
  reminderType?: "email" | "sms" | "app"
  email?: string
  lastSent?: string
  endRepeat?: string
  _id: string
  createdAt?: string
  updatedAt?: string
  isRecurring: boolean
}

/**
 * Lean version of RewardDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RewardDocument.toObject()`. To avoid conflicts with model names, use the type alias `RewardObject`.
 * ```
 * const rewardObject = reward.toObject();
 * ```
 */
export type Reward = {
  name: string
  description: string
  pointsRequired: number
  rewardType: "badge" | "discount" | "giftCard" | "recognition"
  imageUrl?: string
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of RoleDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `RoleDocument.toObject()`. To avoid conflicts with model names, use the type alias `RoleObject`.
 * ```
 * const roleObject = role.toObject();
 * ```
 */
export type Role = {
  roleName: string
  permissions: string[]
  description?: string
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of StreakDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `StreakDocument.toObject()`. To avoid conflicts with model names, use the type alias `StreakObject`.
 * ```
 * const streakObject = streak.toObject();
 * ```
 */
export type Streak = {
  user: User["_id"] | User
  streakCount?: number
  lastCheckIn?: string | null
  longestStreak?: number
  checkInDates: string[]
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of UserLocationCoordinateDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type UserLocationCoordinate = {
  latitude: number
  longitude: number
}

/**
 * Lean version of UserDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`. To avoid conflicts with model names, use the type alias `UserObject`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type User = {
  username: string
  email: string
  password: string
  bio?: string
  profileImage?: string
  coverImage?: string
  name?: string
  role?: "user" | "admin" | "moderator" | "military"
  isVerified?: boolean
  permissions: string[]
  isLocked?: boolean
  active?: boolean
  friends: (User["_id"] | User)[]
  followers: (User["_id"] | User)[]
  following: (User["_id"] | User)[]
  rewards: (Reward["_id"] | Reward)[]
  badges: (Badge["_id"] | Badge)[]
  location: {
    country?: string
    state?: string
    city?: string
    coordinates?: UserLocationCoordinate
  }
  stripeCustomerId?: string
  stripeSubscriptionId?: string
  subscription_status?: "trial" | "active" | "expired" | "canceled" | "past_due"
  subscriptionTier?: "free-trial" | "basic" | "pro" | "elite"
  trial_start_date?: string
  trial_end_date?: string
  subscriptionStartDate?: string
  subscriptionEndDate?: string
  next_billing_date?: string
  billing_cycle?: "monthly" | "yearly"
  interests: string[]
  chatPreferences: {
    preferredGroups: (Chat["_id"] | Chat)[]
    directMessagesOnly?: boolean
  }
  activeStatus?: "online" | "offline"
  settings: {
    notifications: {
      email?: boolean
      sms?: boolean
    }
    privacy: {
      profileVisibility?: "public" | "friends" | "private"
    }
  }
  _id: string
  createdAt?: string
  updatedAt?: string
}

/**
 * Lean version of VerificationTokenDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `VerificationTokenDocument.toObject()`. To avoid conflicts with model names, use the type alias `VerificationTokenObject`.
 * ```
 * const verificationtokenObject = verificationtoken.toObject();
 * ```
 */
export type VerificationToken = {
  user: User["_id"] | User
  token: string
  expiresAt: string
  _id: string
  createdAt?: string
  updatedAt?: string
}
