# ========================
# Global Build Configuration
# ========================
[build]
  command = "npm run build"    # The build command for your project
  publish = "out"              # The correct directory for Next.js static exports
  functions = "netlify/functions"  # The directory for Netlify Functions

# ========================
# Environment Variables
# ========================
[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://api.example.com" # Correct variable for Next.js

# ========================
# Redirects & Rewrites (SPA Support)
# ========================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensures all paths go to index.html for SPA routing

# ========================
# Cache Control for Performance
# ========================
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ========================
# Netlify Functions
# ========================
[functions]
  directory = "netlify/functions"

# ========================
# Deploy Preview Configuration
# ========================
[context.deploy-preview]
  command = "npm run preview"
  publish = "preview-dist"

# ========================
# Production-Specific Configuration
# ========================
[context.production]
  command = "npm run build"
  publish = "out"

# ========================
# Edge Functions (Optional, for performance optimizations)
# ========================
[edge_functions]
  directory = "netlify/edge-functions"
