[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev && npm run build:railway"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.env]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "true"
