// src/constants/roles.ts
export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MODERATOR: "moderator",
  VIEWER: "viewer",
};
  
export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  HANDLE_REPORTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MODERATOR],
  EDIT_SETTINGS: [ROLES.SUPER_ADMIN],
  VIEW_ANALYTICS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MODERATOR, ROLES.VIEWER],
};
  