export const PRICING = [
  {
    id: "free-trial",
    name: "Free Trial",
    description: "Perfect for getting started",
    price: 0,
    yearlyPrice: 0,
    features: [
      "Up to 3 goals",
      "Basic goal tracking",
      "Community access",
      "14-day trial period",
    ],
    isPopular: false,
    trialDays: 14,
  },
  {
    id: "starter",
    name: "Starter",
    description: "Great for individuals",
    price: 9,
    yearlyPrice: 89,
    features: [
      "Up to 10 goals",
      "Streak tracking",
      "Goal analytics",
      "Email support",
    ],
    isPopular: false,
  },
  {
    id: "pro",
    name: "Pro",
    description: "Most popular choice",
    price: 19,
    yearlyPrice: 189,
    features: [
      "Unlimited goals",
      "Direct messaging",
      "Private chat rooms",
      "Advanced analytics",
      "Priority support",
    ],
    isPopular: true,
  },
  {
    id: "premium",
    name: "Premium",
    description: "For serious achievers",
    price: 39,
    yearlyPrice: 389,
    features: [
      "Everything in Pro",
      "Weekly accountability meetings",
      "Personal coach access",
      "Custom integrations",
      "White-glove support",
    ],
    isPopular: false,
  },
]
