// src/constants/envKeys.ts
export const ENV_KEYS = {
  API_BASE_URL: "NEXT_PUBLIC_API_BASE_URL",
  DEFAULT_TIMEZONE: "NEXT_PUBLIC_DEFAULT_TIMEZONE",
  ENABLE_BETA_FEATURES: "NEXT_PUBLIC_ENABLE_BETA_FEATURES",
  SESSION_EXPIRATION_MINUTES: "NEXT_PUBLIC_SESSION_EXPIRATION_MINUTES",
} as const
export type EnvKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS]
